export const ACTION = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  LOGIN_BY_TOKEN: "LOGIN_BY_TOKEN",
  LOAD_CATE_COUNTRY: "LOAD_CATE_COUNTRY",
  LOAD_HOMEPAGE: "LOAD_HOMEPAGE",
  LOAD_FILM: "LOAD_FILM",
  LOAD_TOP_VIEW: "LOAD_TOP_VIEW",
  SET_SEARCH: "SET_SEARCH",
};
